/*
 * demo_mcu_apps / roi_tm  --  fixed-ROI face presence via a Tsetlin Machine
 *
 * The deployment end of the roi_collect -> train_tm pipeline. It draws the SAME
 * fixed ROI box as roi_presence/roi_collect, reads the ROI out of ch1 PSRAM each
 * frame, featurizes it (one "brighter than the ROI mean" bit per cell -- identical
 * to tm_common.featurize on the host), and classifies face/no-face with a Tsetlin
 * Machine trained offline. TM inference is pure bitwise AND/compare/accumulate, so
 * the bit-serial soft core runs it comfortably -- no multiply, no libgcc.
 *
 * The trained model (clause include-masks + sizes) is baked in from tm_model.h,
 * generated by train_tm.py. Each clause is a conjunction of included literals;
 * the first TM_POS clauses vote +1 when they fire, the rest -1; face when the vote
 * reaches TM_THRESHOLD. A "FACE" label lights in the left border while present.
 * Heartbeat (0xE0) = bit7 present, bits[6:0] = vote biased by 64 (host decodes
 * vote = (0xE0 & 0x7F) - 64). Parks; reset the MCU (0xE2) to stop.
 */
#include <stdint.h>
#include "serv_io.h"
#include "tm_model.h"

/* ROI geometry -- MUST match roi_presence.c / roi_collect.c / collect_samples.py */
#define COL_STEP 16
#define ROW_STEP 19200
#define ROI_C0 9
#define ROI_C1 30
#define ROI_R0 1
#define ROI_R1 14
#define ROI_COLS (ROI_C1 - ROI_C0 + 1)
#define ROI_CELLS (ROI_COLS * (ROI_R1 - ROI_R0 + 1))

#if TM_N != ROI_CELLS
#error "tm_model.h TM_N disagrees with the ROI geometry -- retrain (train_tm.py) after changing the ROI"
#endif

/* OSD box-drawing glyphs */
#define BX_H 0x80
#define BX_V 0x81
#define BX_TL 0x82
#define BX_TR 0x83
#define BX_BL 0x84
#define BX_BR 0x85

#define CAM(reg) (*(volatile uint8_t *)(EXT + (reg)))

static const uint8_t col_lut[40] = {
	7, 8,10,11,12,13,14,15,16,17,19,20,21,22,23,24,25,27,28,29,
	30,31,32,33,34,36,37,38,39,40,41,42,44,45,46,47,48,49,50,51
};
static const uint8_t row_lut[16] = { 0,1,2,3,4,5,6,7,9,10,11,12,13,14,15,16 };

static uint8_t bght[ROI_CELLS];      /* per-cell brightness (0..125) */
static uint32_t lit[TM_NWORDS];      /* packed literal vector (2N bits) */

static inline int brightness(uint16_t p)
{
	return ((p >> 11) & 0x1F) + ((p >> 5) & 0x3F) + (p & 0x1F);   /* 0..125 */
}

static inline void osd_go(unsigned row, unsigned col)
{
	OSD_ADDR = (uint16_t)(((row << 6) - (row << 2)) + col);   /* 60*row + col */
}

static void box_outline(unsigned top, unsigned bot, unsigned left, unsigned right)
{
	unsigned w = right - left;
	osd_go(top, left);  OSD_DATA = BX_TL;
	for (unsigned i = 1; i < w; i++) OSD_DATA = BX_H;
	OSD_DATA = BX_TR;
	osd_go(bot, left);  OSD_DATA = BX_BL;
	for (unsigned i = 1; i < w; i++) OSD_DATA = BX_H;
	OSD_DATA = BX_BR;
	for (unsigned r = top + 1; r < bot; r++) {
		osd_go(r, left);  OSD_DATA = BX_V;
		osd_go(r, right); OSD_DATA = BX_V;
	}
}

/* read the ROI, build the packed literal vector (features then their negations) */
static void featurize(void)
{
	int32_t sum = 0;
	unsigned i = 0;
	uint32_t rowbase = (uint32_t)ROI_R0 * ROW_STEP;
	for (int rr = ROI_R0; rr <= ROI_R1; rr++) {
		uint32_t addr = rowbase + (uint32_t)ROI_C0 * COL_STEP;
		for (int cc = ROI_C0; cc <= ROI_C1; cc++) {
			int v = brightness(psram_read16(addr));
			bght[i++] = (uint8_t)v;
			sum += v;
			addr += COL_STEP;
		}
		rowbase += ROW_STEP;
	}
	/* ROI mean by repeated subtraction (no mul/div -> no libgcc). b[i] > floor(sum/N)
	 * is bit-identical to the host's b[i]*N > sum for integer brightness. */
	int mean = 0;
	for (int32_t acc = sum; acc >= TM_N; acc -= TM_N)
		mean++;

	for (unsigned w = 0; w < TM_NWORDS; w++)
		lit[w] = 0;
	for (i = 0; i < TM_N; i++) {
		unsigned k = (bght[i] > mean) ? i : (TM_N + i);
		lit[k >> 5] |= 1u << (k & 31);
	}
}

/* Tsetlin Machine vote: each clause fires iff every included literal is 1. */
static int tm_vote(void)
{
	int vote = 0;
	for (unsigned j = 0; j < TM_CLAUSES; j++) {
		const unsigned int *m = tm_mask[j];
		int out = 1;
		for (unsigned w = 0; w < TM_NWORDS; w++) {
			if ((lit[w] & m[w]) != m[w]) { out = 0; break; }
		}
		if (out)
			vote += (j < TM_POS) ? 1 : -1;
	}
	return vote;
}

void main(void)
{
	osd_clear_enable();
	while (!psram_calibrated())
		;
	CAM(0x14) = 0x3A;                /* COM9: AGC ceiling -> 16x */
	CAM(0x13) = 0xE7;                /* COM8: enable AWB */

	box_outline(row_lut[ROI_R0], row_lut[ROI_R1], col_lut[ROI_C0], col_lut[ROI_C1]);

	int prev = -1;
	for (;;) {
		psram_grab_frame();
		featurize();
		int vote = tm_vote();
		int present = (vote >= TM_THRESHOLD);

		if (present != prev) {
			osd_go(8, 1);
			osd_puts(present ? "FACE" : "    ");
			prev = present;
		}
		/* bit7 = present; bits[6:0] = vote + 64 (host: vote = (hb & 0x7F) - 64) */
		int biased = vote + 64;
		if (biased < 0) biased = 0;
		if (biased > 127) biased = 127;
		HEARTBEAT = (uint16_t)((present ? 0x80 : 0) | (biased & 0x7F));
	}
}
