/*
 * demo_mcu_apps / roi_tm  --  fixed-ROI face presence via a Tsetlin Machine
 *
 * The deployment end of the roi_collect -> train_tm pipeline. It draws the SAME
 * fixed ROI box as roi_presence/roi_collect, reads the ROI out of ch1 PSRAM each
 * frame, featurizes it with an 8-neighbour Local Binary Pattern (LBP) -- 2x2
 * block-average to an 11x7 grid, then 8 "neighbour >= centre" bits per interior
 * cell (45 cells * 8 = 360 boolean features), identical to tm_common.featurize on
 * the host -- and classifies face/no-face with a Tsetlin Machine trained offline.
 * Inference and featurization are pure integer compares + bitwise AND/accumulate,
 * so the bit-serial soft core runs it comfortably -- no multiply, divide, or float.
 *
 * The trained model (clause include-masks + sizes) is baked in from tm_model.h,
 * generated by train_tm.py. Each clause is a conjunction of included literals;
 * the first TM_POS clauses vote +1 when they fire, the rest -1; face when the vote
 * reaches TM_THRESHOLD. A "FACE" label lights in the left border while present.
 * Heartbeat (0xE0) = bit7 present, bits[6:0] = vote biased by 64 (host decodes
 * vote = (0xE0 & 0x7F) - 64). Parks; reset the MCU (0xE2) to stop.
 */
#include <stdint.h>
#include "serv_io.h"
#include "tm_model.h"

/* ROI geometry -- MUST match roi_presence.c / roi_collect.c / collect_samples.py */
#define COL_STEP 16
#define ROW_STEP 19200
#define ROI_C0 9
#define ROI_C1 30
#define ROI_R0 1
#define ROI_R1 14
#define ROI_COLS (ROI_C1 - ROI_C0 + 1)
#define ROI_ROWS (ROI_R1 - ROI_R0 + 1)
#define ROI_CELLS (ROI_COLS * ROI_ROWS)

/* LBP featurization: 2x2 block-average downsample, then 8-neighbour LBP on the
 * interior of the downsampled grid. MUST match tm_common.py. */
#define DSW (ROI_COLS / 2)
#define DSH (ROI_ROWS / 2)
#define LBP_FEATURES (((DSW - 2) * (DSH - 2)) * 8)

#if TM_N != LBP_FEATURES
#error "tm_model.h TM_N disagrees with the LBP feature count -- retrain (train_tm.py)"
#endif

/* OSD box-drawing glyphs */
#define BX_H 0x80
#define BX_V 0x81
#define BX_TL 0x82
#define BX_TR 0x83
#define BX_BL 0x84
#define BX_BR 0x85

#define CAM(reg) (*(volatile uint8_t *)(EXT + (reg)))

static const uint8_t col_lut[40] = {
	7, 8,10,11,12,13,14,15,16,17,19,20,21,22,23,24,25,27,28,29,
	30,31,32,33,34,36,37,38,39,40,41,42,44,45,46,47,48,49,50,51
};
static const uint8_t row_lut[16] = { 0,1,2,3,4,5,6,7,9,10,11,12,13,14,15,16 };

static uint8_t bght[ROI_CELLS];      /* per-cell brightness (0..125) */
static uint8_t ds[DSH * DSW];        /* 2x2 block-averaged brightness grid */
static uint32_t lit[TM_NWORDS];      /* packed literal vector (2N bits) */

static inline int brightness(uint16_t p)
{
	return ((p >> 11) & 0x1F) + ((p >> 5) & 0x3F) + (p & 0x1F);   /* 0..125 */
}

static inline void osd_go(unsigned row, unsigned col)
{
	OSD_ADDR = (uint16_t)(((row << 6) - (row << 2)) + col);   /* 60*row + col */
}

static void box_outline(unsigned top, unsigned bot, unsigned left, unsigned right)
{
	unsigned w = right - left;
	osd_go(top, left);  OSD_DATA = BX_TL;
	for (unsigned i = 1; i < w; i++) OSD_DATA = BX_H;
	OSD_DATA = BX_TR;
	osd_go(bot, left);  OSD_DATA = BX_BL;
	for (unsigned i = 1; i < w; i++) OSD_DATA = BX_H;
	OSD_DATA = BX_BR;
	for (unsigned r = top + 1; r < bot; r++) {
		osd_go(r, left);  OSD_DATA = BX_V;
		osd_go(r, right); OSD_DATA = BX_V;
	}
}

/* set literal `idx` from a feature bit: feature at bit idx, negation at bit TM_N+idx */
#define SET_FEAT(cond) do {                              \
	unsigned k = (cond) ? idx : (TM_N + idx);            \
	lit[k >> 5] |= 1u << (k & 31);                       \
	idx++;                                               \
} while (0)

/* read the ROI, 2x2 block-average to ds[], then build the packed LBP literal vector */
static void featurize(void)
{
	unsigned i = 0;
	uint32_t rowbase = (uint32_t)ROI_R0 * ROW_STEP;
	for (int rr = ROI_R0; rr <= ROI_R1; rr++) {
		uint32_t addr = rowbase + (uint32_t)ROI_C0 * COL_STEP;
		for (int cc = ROI_C0; cc <= ROI_C1; cc++) {
			bght[i++] = (uint8_t)brightness(psram_read16(addr));
			addr += COL_STEP;
		}
		rowbase += ROW_STEP;
	}

	/* 2x2 block average (running offsets -> no multiply) */
	unsigned o = 0, row0 = 0;
	for (int r = 0; r < DSH; r++) {
		unsigned row1 = row0 + ROI_COLS, cc = 0;
		for (int c = 0; c < DSW; c++) {
			int s = bght[row0 + cc] + bght[row0 + cc + 1]
			      + bght[row1 + cc] + bght[row1 + cc + 1];
			ds[o++] = (uint8_t)(s >> 2);
			cc += 2;
		}
		row0 += 2 * ROI_COLS;
	}

	/* 8-neighbour LBP over the interior -> literals (order: TL,T,TR,L,R,BL,B,BR) */
	for (unsigned w = 0; w < TM_NWORDS; w++)
		lit[w] = 0;
	unsigned idx = 0, base = DSW;
	for (int r = 1; r < DSH - 1; r++) {
		for (int c = 1; c < DSW - 1; c++) {
			unsigned b = base + c, up = b - DSW, dn = b + DSW;
			int ctr = ds[b];
			SET_FEAT(ds[up - 1] >= ctr);
			SET_FEAT(ds[up]     >= ctr);
			SET_FEAT(ds[up + 1] >= ctr);
			SET_FEAT(ds[b - 1]  >= ctr);
			SET_FEAT(ds[b + 1]  >= ctr);
			SET_FEAT(ds[dn - 1] >= ctr);
			SET_FEAT(ds[dn]     >= ctr);
			SET_FEAT(ds[dn + 1] >= ctr);
		}
		base += DSW;
	}
}

/* Tsetlin Machine vote: each clause fires iff every included literal is 1. */
static int tm_vote(void)
{
	int vote = 0;
	for (unsigned j = 0; j < TM_CLAUSES; j++) {
		const unsigned int *m = tm_mask[j];
		int out = 1;
		for (unsigned w = 0; w < TM_NWORDS; w++) {
			if ((lit[w] & m[w]) != m[w]) { out = 0; break; }
		}
		if (out)
			vote += (j < TM_POS) ? 1 : -1;
	}
	return vote;
}

void main(void)
{
	osd_clear_enable();
	while (!psram_calibrated())
		;
	CAM(0x14) = 0x3A;                /* COM9: AGC ceiling -> 16x */
	CAM(0x13) = 0xE7;                /* COM8: enable AWB */

	box_outline(row_lut[ROI_R0], row_lut[ROI_R1], col_lut[ROI_C0], col_lut[ROI_C1]);

	int prev = -1;
	for (;;) {
		psram_grab_frame();
		featurize();
		int vote = tm_vote();
		int present = (vote >= TM_THRESHOLD);

		if (present != prev) {
			osd_go(8, 1);
			osd_puts(present ? "FACE" : "    ");
			prev = present;
		}
		/* bit7 = present; bits[6:0] = vote + 64 (host: vote = (hb & 0x7F) - 64) */
		int biased = vote + 64;
		if (biased < 0) biased = 0;
		if (biased > 127) biased = 127;
		HEARTBEAT = (uint16_t)((present ? 0x80 : 0) | (biased & 0x7F));
	}
}
