/*
 * demo_mcu_apps / roi_tm  --  fixed-ROI face presence via a Tsetlin Machine
 *
 * The deployment end of the roi_collect -> train_tm pipeline. It draws the SAME
 * fixed ROI box as roi_presence/roi_collect, reads the ROI out of ch1 PSRAM each
 * frame, and featurizes it (identical to tm_common.featurize on the host): 2x2
 * block-average to an 11x7 grid, then luma LBP (8 "neighbour >= centre" bits per
 * interior cell = 360) + 3 colour bits per cell (R>G, R>B, skin = 231) = 591
 * boolean features. Colour is the key face-vs-background discriminator. A Tsetlin
 * Machine (trained offline) then classifies face/no-face. Featurization + inference
 * are pure integer compares + bitwise AND/accumulate -- no multiply, divide, float.
 *
 * The trained model (clause include-masks + sizes) is baked in from tm_model.h,
 * generated by train_tm.py. Each clause is a conjunction of included literals;
 * the first TM_POS clauses vote +1 when they fire, the rest -1; face when the net
 * vote reaches TM_THRESHOLD. The left border shows the live result: "FACE"/"----",
 * the processing rate "FPS NN" (loop iterations/sec off the 1 Hz uptime counter),
 * and the confidence as two clause tallies "F NN N NN" (F = face clauses fired,
 * N = non-face clauses fired; the gap between them is how decisive the call is).
 * Heartbeat (0xE0) = bit7 present, bits[6:0] = vote biased by 64 (host decodes
 * vote = (0xE0 & 0x7F) - 64). Parks; reset the MCU (0xE2) to stop.
 */
#include <stdint.h>
#include "serv_io.h"
#include "tm_model.h"
#include "roi_features.h"   /* ROI_COLS/ROI_ROWS/ROI_CELLS + roi_featurize() */

/* PSRAM addressing of the ROI -- MUST match roi_presence.c / roi_collect.c.
 * (ROI_C0..R1 span exactly ROI_COLS x ROI_ROWS cells from roi_features.h.) */
#define COL_STEP 16
#define ROW_STEP 19200
#define ROI_C0 9
#define ROI_C1 30
#define ROI_R0 1
#define ROI_R1 14

/* OSD box-drawing glyphs */
#define BX_H 0x80
#define BX_V 0x81
#define BX_TL 0x82
#define BX_TR 0x83
#define BX_BL 0x84
#define BX_BR 0x85

#define CAM(reg) (*(volatile uint8_t *)(EXT + (reg)))

static const uint8_t col_lut[40] = {
	7, 8,10,11,12,13,14,15,16,17,19,20,21,22,23,24,25,27,28,29,
	30,31,32,33,34,36,37,38,39,40,41,42,44,45,46,47,48,49,50,51
};
static const uint8_t row_lut[16] = { 0,1,2,3,4,5,6,7,9,10,11,12,13,14,15,16 };

static uint16_t roi[ROI_CELLS];      /* raw RGB565 per cell */
static uint32_t lit[TM_NWORDS];      /* packed literal vector (2N bits) */

static inline void osd_go(unsigned row, unsigned col)
{
	OSD_ADDR = (uint16_t)(((row << 6) - (row << 2)) + col);   /* 60*row + col */
}

static void box_outline(unsigned top, unsigned bot, unsigned left, unsigned right)
{
	unsigned w = right - left;
	osd_go(top, left);  OSD_DATA = BX_TL;
	for (unsigned i = 1; i < w; i++) OSD_DATA = BX_H;
	OSD_DATA = BX_TR;
	osd_go(bot, left);  OSD_DATA = BX_BL;
	for (unsigned i = 1; i < w; i++) OSD_DATA = BX_H;
	OSD_DATA = BX_BR;
	for (unsigned r = top + 1; r < bot; r++) {
		osd_go(r, left);  OSD_DATA = BX_V;
		osd_go(r, right); OSD_DATA = BX_V;
	}
}

/* read the ROI out of ch1 PSRAM, then featurize (shared roi_features.h) */
static void featurize(void)
{
	unsigned i = 0;
	uint32_t rowbase = (uint32_t)ROI_R0 * ROW_STEP;
	for (int rr = ROI_R0; rr <= ROI_R1; rr++) {
		uint32_t addr = rowbase + (uint32_t)ROI_C0 * COL_STEP;
		for (int cc = ROI_C0; cc <= ROI_C1; cc++) {
			roi[i++] = psram_read16(addr);
			addr += COL_STEP;
		}
		rowbase += ROW_STEP;
	}
	roi_featurize(roi, lit);
}

/* Tsetlin Machine vote (sparse model): clause j fires iff all of its included
 * literals (the next tm_clause_len[j] entries of tm_lit) are 1. Returns the two
 * raw tallies -- *face = positive clauses (j<TM_POS) that fired, *nonface =
 * negative clauses that fired. The net class vote is *face - *nonface. */
static void tm_votes(int *face, int *nonface)
{
	int f = 0, nf = 0;
	unsigned off = 0;
	for (unsigned j = 0; j < TM_CLAUSES; j++) {
		unsigned n = tm_clause_len[j];
		int out = 1;
		for (unsigned t = 0; t < n; t++) {
			unsigned L = tm_lit[off + t];
			if (!((lit[L >> 5] >> (L & 31)) & 1u)) { out = 0; break; }
		}
		off += n;
		if (out) {
			if (j < TM_POS) f++;
			else nf++;
		}
	}
	*face = f;
	*nonface = nf;
}

void main(void)
{
	osd_clear_enable();
	while (!psram_calibrated())
		;
	CAM(0x14) = 0x3A;                /* COM9: AGC ceiling -> 16x */
	CAM(0x13) = 0xE7;                /* COM8: enable AWB */

	box_outline(row_lut[ROI_R0], row_lut[ROI_R1], col_lut[ROI_C0], col_lut[ROI_C1]);
	osd_go(10, 1); osd_puts("FPS --");
	osd_go(12, 1); osd_puts("F -- N --");

	int prev = -1, prev_f = -1, prev_nf = -1;
	unsigned passes = 0, last = uptime_lo();
	for (;;) {
		psram_grab_frame();
		featurize();
		int face, nonface;
		tm_votes(&face, &nonface);             /* face / non-face clause tallies */
		int vote = face - nonface;
		int present = (vote >= TM_THRESHOLD);
		passes++;

		/* processing FPS: loop iterations between 1 Hz uptime ticks (no RTC) */
		unsigned now = uptime_lo();
		if (now != last) {
			osd_go(10, 1); osd_puts("FPS ");
			osd_put_dec2(passes > 99 ? 99 : passes);
			passes = 0; last = now;
		}
		if (present != prev) {
			osd_go(8, 1);
			osd_puts(present ? "FACE" : "----");
			prev = present;
		}
		/* confidence as two clause-vote counters: F = face votes, N = non-face */
		if (face != prev_f || nonface != prev_nf) {
			osd_go(12, 1);
			osd_puts("F "); osd_put_dec2(face);
			osd_puts(" N "); osd_put_dec2(nonface);
			prev_f = face; prev_nf = nonface;
		}
		/* bit7 = present; bits[6:0] = vote + 64 (host: vote = (hb & 0x7F) - 64) */
		int biased = vote + 64;
		if (biased < 0) biased = 0;
		if (biased > 127) biased = 127;
		HEARTBEAT = (uint16_t)((present ? 0x80 : 0) | (biased & 0x7F));
	}
}
