// ===========================================================================
// AUTO-GENERATED by CMake from platform.json -- DO NOT EDIT.
// Change the values in platform.json and re-run cmake to regenerate this file.
// ===========================================================================
`ifndef PLATFORM_CONFIG_VH
`define PLATFORM_CONFIG_VH

`define PLATFORM_INPUT_FRAME_WIDTH  640
`define PLATFORM_INPUT_FRAME_HEIGHT 480
`define PLATFORM_SCREEN_WIDTH       480
`define PLATFORM_SCREEN_HEIGHT      272
`define PLATFORM_EMIT_ROW_SIZE      640

`endif
